services:
  db:
    image: mysql:8.0
    container_name: memory_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"   # <- CAMBIADO (antes era 3306:3306)
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: memory_web
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
