# Generated by Django 5.2.4 on 2025-08-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Difícil')], max_length=10)),
                ('won', models.BooleanField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
