# Generated by Django 5.2.4 on 2025-08-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemoryGameMVC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
