# Generated by Django 5.2.4 on 2025-08-10 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemoryGameMVC', '0002_remove_gameresult_difficulty_gameresult_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='played_at',
            new_name='date_played',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
