# Generated by Django 5.2.4 on 2025-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemoryGameMVC', '0003_rename_played_at_gameresult_date_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
